name: Publish coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    name: Generate report
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22.14.0

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run tests and generate coverage report
        run: npm run test:cov

      - name: Generate coverage badge
        uses: jpb06/coverage-badges-action@latest
        with:
          branches: main
          badges-icon: jest
          commit-message: 'github-actions[bot]: update coverage badge'
          commit-user: github-actions
          commit-user-email: github-actions@users.noreply.github.com
