name: Generate coverage badge

on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22.14.0

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run tests and generate coverage report
        run: npm run test:cov

      - name: Generate coverage badge
        uses: jpb06/jest-badges-action@v1.2.0
        with:
          branches: main
          coverage-summary-path: coverage/coverage-final.json

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "chore: update coverage badge" || exit 0
          git push
